### PR TITLE
Repo add file enhancement

### PR DESCRIPTION
**Pull request by thereseanders**
This PR conducts a number of changes on repo_add_file()`
-  Adds `folder` parameter to the `repo_add_file()` function. It is `NULL` by default. This change is necessary to allow the usage of `repo_add_file()` with the new peer review functions, for example to batch place reviewer feedback forms into author-specific folders on a reviewers' repositories. 
- Updates/changes the documentation and examples.
- Removes unnecessary parameters from `purrr::walk`
- Removes turning empty message into list (causes `repo_put_file` to fail).

### CODE REVIEW

**Comment by thereseanders** [comment]
Changed the `check_file_modification` test to `file_exists`. The current form of `check_file_modification` will return TRUE on deleted files and won't allow to add new files. This causes functions calling `repo_add_file` to fail.

We should talk about whether we want to include the `check_file_modification` again that checks for student versus admin modifications.

**Comment by thereseanders** [comment]
Based on our conversation, I implemented the following:

1. Changed `file_exists()` to `file_exists_current()`
2. Wrote new function `file_exists()` that uses `check_file_modification()` to see whether file ever exists, and only if `TRUE` is returned uses  `file_exists_current()` (that is costly in terms of calls to the API).

**Currently not implemented**
- Check and message who modified file. 
- Potentially use `GET` call to check for existence of file rather than `check_file_modification ()`

**Comment by thereseanders** [comment]
An alternative way to implement this would be to list all files in the repo (**note that folders are treated as file names**) and then check whether a file name is in the list.

``` r
github_api_get_repo_get_files = function(repo, branch) {
  arg_is_chr_scalar(repo)

  gh::gh(
    "GET /repos/:owner/:repo/contents",
    owner = get_repo_owner(repo),
    repo = get_repo_name(repo),
    ref = branch,
    .token = github_get_token(),
    .limit = get_github_api_limit()
  )
}

get_files = function(repo, branch){

  arg_is_chr(repo)

  purrr::map_dfr(repo,
                 function(repo) {
                   res = purrr::safely(github_api_get_repo_get_files)(repo = repo, branch = branch)

                   status_msg(
                     res,
                     fail = glue::glue("Failed to retrieve contents of {usethis::ui_value(repo)}.")
                     )

                   files = result(res)

                   if (empty_result(files)) {
                     tibble::tibble(
                       name = character(),
                       type = character()
                     )
                   } else {
                     tibble::tibble(
                       name = purrr::map_chr(files, "name"),
                       type = purrr::map_chr(files, "type")
                     )
                   }
                 })
}

file_exists = function(repo, file, branch = "master", verbose = TRUE) {

  purrr::pmap_lgl(
    list(repo, file, branch),
    function(repo, file, branch) {
      files = get_files(repo)
      files = files[files$type == "file",]
      file %in% files$name
      }
  )
}
```

**Comment by thereseanders** [comment]
I made more modifications on `repo_add_file()` and helper functions.

- `repo_add_file()` now calls `check_file_modification()` as part of the commit messaging.
- added new function `check_file_everexist()` that checks for a length of the output of `get_committer() > 0`.
- Only if `check_file_everexist()` evaluates to true is the costly call to `file_exists_current()` implemented. **We should think about whether to replace this functionality with a GET call instead.
- I will use a `purrr::safely(github_api_repo_get_file)()` call in the peer review functions whenever possible to reduce calls to `check_file_everexist()`.

**Comment by thereseanders** [comment]
This PR makes the following changes:
- adds `folder` parameter to `repo_add_file()`
- enhances error message for `file_status` by printing specifically which file could not be found
- changes `file_exist()` to use new `repo_files()` function (that relies on `github_api_repo_get_tree()`). 
- `repo_add_file()` calls `file_exist()`, rather than `check_file_modification()` when deciding whether to add file.
- `check_file_modification()` is called in the messaging if the file exists and `overwrite == F`
- merged upstream changes
- Updates/changes the documentation and examples.
- Removes unnecessary parameters from purrr::walk
- Removes turning empty message into list (causes repo_put_file to fail).

**Comment by rundel** [comment]
Looks good, I made a slight simplifying change to use fs instead of a regex to prepend the folder to the repo path.

**Comment by rundel** [comment]
Only small concern I have is that I found the folder parameter name slightly confusing without reading the docs. Since this refers to something that will happen only in the repository maybe consider a prefix like `repo_` or `dest_` (neither are particularly satisfying but I dont have a better suggestion atm).

**Comment by thereseanders** [comment]
Oh the `fs::path()` solution is great. Thank you! 

I changed the `folder` parameter to `repo_folder`.

**Pull request merged**
